MIPS: generic: Remove undefined image 'ramdisk' from jaguar2
Currently a MIPS allmodconfig build fails with:

Error: configuration 'pcb110' references undefined image 'ramdisk' in property 'ramdisk'
make[3]: *** [../arch/mips/boot/Makefile:173: arch/mips/boot/vmlinux.gz.itb] Error 1
make[2]: *** [../arch/mips/Makefile:403: vmlinux.gz.itb] Error 2

Remove the stale ramdisk references.

Assisted-by: LLM
Signed-off-by: Jeff Johnson <jeff.johnson@oss.qualcomm.com>
(cherry picked from commit bfde6fe207cfdaa9a00f2d3719542dda5d505d6c)